### ISSUE TITLE
ControlPanel.output_control issue

### ISSUE THREAD

**Issue by timov43** [ryanhz/osdp-python#1]
I was not able to run the ControlPanel.output_control() before I changed the class OutputControls into the following form:

> 
> class OutputControls:
> 
>         def __init__(self, controls):
>                 self.controls = controls
> 
>         def build_data(self) -> bytes:
>                 data = bytearray()
>                 # for control in controls:
>                 for control in self.controls:
>                         # data.extend(control.build_data())
>                         data.append(control)
>                 return bytes(data)
> 

What do you think?

**Comment by ryanhz** [comment]
Yes, it is a typo. Fixed now.
