### ISSUE TITLE
Running on Pi 4

### ISSUE THREAD

**Issue by scroggyg** [ryanhz/osdp-python#5]
I have created a new Debian installation on a PI 4.
I have installed using pip install -U osdp
It installs successfully into the python2.7/site-packages/osdp
When I enter python and try to run 
>>> from osdp import * 
Traceback (most recent call last):
File <"stdin>". line 1, in <module>
File"home/pi/.local/lib/python2.7/site-packages/osdp/__init__.py", line 14 in <module> from .-types_import(
File "/home/pi/.local/lib/python2.7/site-packages/osdp/_types.py", line 39 
def __init__(self, sequence: init, use_crc: bool, has_security_control_block: bool):
                                        ^ 
SyntaxError: invalid syntax

**Comment by ryanhz** [comment]
It only support python3.5+

**Comment by scroggyg** [comment]
Ryan did you see the changes we posted to get the secure session working?
Best regards
George Redpath

Sent from my iPhone

On 31 Jul 2020, at 04:59, Ryan <notifications@github.com> wrote:

﻿

It only support python3.5+

**Comment by ryanhz** [comment]
Hi George,  where did you posted the changes to get the secure session working?

**Comment by scroggyg** [comment]
It was a colleague Thomas McRoberts, I have included him in the link, we are making some OSDP products, so we are using your software for test, and found issues with the Secure channel implementation.
I have included Thomas in the email, he can give more detail.
Regards
George

**Comment by ryanhz** [comment]
Oh, nice.  The python code was ported from @dbytedreamer's OSDP.Net.  We haven't used the secure channel yet, so it is not properly tested (I don't have sample data to test).   Feel free to fork and make change directly.

**Comment by scroggyg** [comment]
No problem Ryan, we will also post some of our test scripts.
I will try and load python 3.5 on the PI and let you know how we get on.
Best regards
George

**Comment by Thomac02** [comment]
Hi Ryan, I have tested the secure session with one of our devices, just had to make a few minor changes to get it working. I forked the lib, you can see my changes at https://github.com/Thomac02/osdp-python. Thanks btw, its a great library!

**Comment by ryanhz** [comment]
Cool.  I have merged your changes.
I think you can use logger instead of print for debugging.

Do you have test cases?

**Comment by Thomac02** [comment]
I didn't think of using logger, that's much better. I was using a very basic script to test, currently working on proper unit tests like those you've already done. I'll push them once I've finished.

**Comment by scroggyg** [comment]
Ryan, I am picking this up again, a quick question, we are using a Pi compute module/or a hat. Have you tested GPIO for the data enable on the RS485 transceiver, or have you only used a USB 485 convertor. I know the RTS response can be slow, or need low level code to read the status registers on the UART.

**Comment by ryanhz** [comment]
Hi,  we were using SC16IS752 on a Pi hat, similar to this one:
https://www.waveshare.com/wiki/Serial_Expansion_HAT

This link also contains instructions on how to configure the driver.

**Comment by scroggyg** [comment]
Thanks Ryan, so directly using UART pins on the hat isn’t supported?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanhz** [comment]
Yes, you can use the UART on Pi with a RS485 adapter.  By default Pi's UART is configured for serial console, you may want to change the setting in /boot/config.txt

RS485 is half-duplex, so no need for CTS or RTS signal.

**Comment by scroggyg** [comment]
I have got the UART working, the issue is there is no control for the Data Direction link on the RS485 transceiver.
The default control line for the Data Direction, he refers to it a DE.
Here is a good article on the issue, basically you have to drive the DE line immediately after the last bit leaves the PIN, as often it is double buffered.
How to Use a Raspberry Pi and Custom RS485 HAT With Modbus Protocol | Raspberry Pi | Maker Pro<https://maker.pro/raspberry-pi/tutorial/a-custom-rs485-hat-to-use-modbus-with-raspberry-pi>
The component on the HAT you suggested has an auto switch over mode
SC16IS752; SC16IS762 Dual UART with I2C-bus/SPI interface, 64 bytes of transmit and receive FIFOs, IrDA SIR built-in support (nxp.com)<https://www.nxp.com/docs/en/data-sheet/SC16IS752_SC16IS762.pdf>
Section 9.1 in the datasheet.
Many thanks
George

**Comment by ryanhz** [comment]
I think to make your case working with OSDP, you have to provide your own version of `OsdpConnection`, just sublass `OsdpConnection`, it is very simple, in your `OsdpConnection` implement, set the GPIO connect to DE/RE to high when sending, to low when receiving. Because RS485 is not full-duplex, DE/RE pin is either high or low at a time.  Your `OsdpConnection` implement class control the direction of communication via DE/RE pin.

**Comment by scroggyg** [comment]
Thanks Ryan, we will give that a try.
Best regards
George
